apiVersion: v2
appVersion: "1.0"
description: A Helm chart for pip-channel-management App
name: pip-channel-management
home: https://github.com/hmcts/pip-channel-management
version: 0.0.2
maintainers:
  - name: HMCTS PIP Team
dependencies:
  - name: java
    version: 3.6.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo'
