java:
  aadIdentityName: pip
  ingressHost: pip-channel-management.{{ .Values.global.environment }}.platform.hmcts.net
  applicationPort: 8181
  image: 'sdshmctspublic.azurecr.io/pip/channel-management:latest'
  environment:
