java:
  aadIdentityName: pip
  ingressHost: pip-channel-management.{{ .Values.global.environment }}.platform.hmcts.net
  applicationPort: 8181
  image: 'sdshmctspublic.azurecr.io/pip/channel-management:latest'
  keyVaults:
    pip-ss-kv:
      excludeEnvironmentSuffix: false
      resourceGroup: pip-ss-{{ .Values.global.environment }}-rg
      usePodIdentity: true
      secrets:
        - name: app-pip-channel-management-stg-id
          alias: CLIENT_ID
        - name: app-pip-channel-management-stg-pwd
          alias: CLIENT_SECRET
        - name: app-tenant-id
          alias: TENANT_ID
        - name: app-pip-channel-management-stg-api-id
          alias: APP_URI
  environment:
